### PR TITLE
R4R: Fix the wrong range of auth/gasPriceThreshold

### LINKED ISSUE #1007: [p3] Left closed interval error in ERROR message of gasPriceThreshold
To reproduce：

echo 1234567890 | iriscli gov submit-proposal --title="t" --description="t" --type="ParameterChange" --deposit="2000iris"  --param='auth/gasPriceThreshold=0' --from=v0 --chain-id=shilei-qa --fee=0.004iris  --commit

ERROR: {"codespace":"sdk","code":600,"message":"Gas price threshold (0) should be [0, 10^18iris-atto]"}

-----------------------
Should be (0, 10^18iris-atto]

### PR DESCRIPTION
**Pull request by MrXJC**
Close #1007

### CODE REVIEW

File: modules/auth/params.go [hunk 1]
```diff
@@ -52,7 +52,7 @@ func (p *Params) Validate(key string, value string) (interface{}, sdk.Error) {
 		if !ok {
 			return nil, params.ErrInvalidString(value)
 		}
-		if !threshold.GT(MinimumGasPrice) || threshold.GT(MaximumGasPrice) {
+		if threshold.LT(MinimumGasPrice) || threshold.GT(MaximumGasPrice) {
```
Comment (wukongcheng) [inline modules/auth/params.go]: GasPriceThreshold range is (0, 1iris]. So the threshold can not be equal with MinimumGasPrice.
