### PR TITLE
R4R: Fix the Unit dislocation in ERROR message of ParameterChange/slashing

### LINKED ISSUE #1014: [p3] Unit dislocation in ERROR message of ParameterChange/slashing
echo 1234567890 | iriscli gov submit-proposal --title="t" --description="t" --type="ParameterChange" --deposit="2000iris"  --param='slashing/SlashFractionDoubleSign=0.11' --from=v0 --chain-id=shilei-qa --fee=0.004iris  --commit

ERROR: {"codespace":"sdk","code":800,"message":"Slash MinSignedPerWindow/SlashFractionDoubleSign/SlashFractionDowntime [1100000000] should be between [0.01, 0.1] "}

should be ： 【 [0.11] should be between [0.01, 0.1] 】

---------
echo 1234567890 | iriscli gov submit-proposal --title="t" --description="t" --type="ParameterChange" --deposit="2000iris"  --param='slashing/SlashFractionDowntime=0.004' --from=v0 --chain-id=shilei-qa --fee=0.004iris  --commit

ERROR: {"codespace":"sdk","code":800,"message":"Slash MinSignedPerWindow/SlashFractionDoubleSign/SlashFractionDowntime [40000000] should be between [0.005, 0.1] "}

should be ： 【 [0.004] should be between [0.01, 0.1] 】

----------------------------------
iris version 3894c521bd7d6b83075262026b6dfaa395808bae
0.10.0-rc0-3894c52-0

### PR DESCRIPTION
**Pull request by MrXJC**
Close #1014

### CODE REVIEW

File: modules/slashing/params.go [hunk 1]
```diff
@@ -237,21 +237,21 @@ func validateSignedBlocksWindow(p int64) sdk.Error {
 
 func validateMinSignedPerWindow(p sdk.Dec) sdk.Error {
 	if p.LT(sdk.NewDecWithPrec(5, 1)) || p.GT(sdk.NewDecWithPrec(9, 1)) {
-		return sdk.NewError(params.DefaultCodespace, params.CodeInvalidSlashParams, fmt.Sprintf("Slash MinSignedPerWindow/SlashFractionDoubleSign/SlashFractionDowntime [%s] should be between [0.5, 0.9] ", p))
+		return sdk.NewError(params.DefaultCodespace, params.CodeInvalidSlashParams, fmt.Sprintf("Slash MinSignedPerWindow/SlashFractionDoubleSign/SlashFractionDowntime [%s] should be between [0.5, 0.9] ", p.String()))
```
Comment (wukongcheng) [inline modules/slashing/params.go]: improve the error msg
