### PR TITLE
R4R: check destination address is a trustee when TaxUsage proposal execute

### LINKED ISSUE #933: [priority:p2] Gov fail to verify the identity of trustee before withdrawing fee tax from the blockchain's tax pool
Describe the bug
Gov verify the identity of trustee while submitting proposal but not after vote through

To Reproduce

    1. execute add-trustee to add one trustee (eg. user_1)
    2. submit a TxTaxUsage proposal (specify --dest-address=user_1_faa)
    3. execute delete-trustee to remove user_1 from trustee list
    4. vote "yes" for the previous proposal

    notice that tax fee is withdrawed to a non-trustee account

Expected behavior
check the identity of trustee before withdrawing fee tax

Screenshots
N/A

Desktop (please complete the following information):

    1 validator nodes

Smartphone (please complete the following information):
N/A

Additional context
N/A

### PR DESCRIPTION
**Pull request by chengwenxi**
Closes #933

### CODE REVIEW

File: modules/gov/execute.go [hunk 1]
```diff
@@ -22,9 +22,17 @@ func Execute(ctx sdk.Context, k Keeper, p Proposal) (err error) {
...
 func TaxUsageProposalExecute(ctx sdk.Context, k Keeper, p *TaxUsageProposal) (err error) {
+	logger := ctx.Logger().With("module", "gov")
 	burn := false
 	if p.Usage == UsageTypeBurn {
 		burn = true
+	} else {
+		_, found := k.gk.GetTrustee(ctx, p.DestAddress)
+		if !found {
+			logger.Info("Execute TaxUsageProposal Failure", "info",
+				fmt.Sprintf("the destination address [%s] is not a trustee now", p.DestAddress))
```
Comment (HaoyangLiu) [inline modules/gov/execute.go]: `logger.Error()`
