### PR TITLE
R4R: bug fix for v0.8

### LINKED ISSUE #739: Protocol buffer comments' attribute empty value check need to be done.
```go
		value := strings.TrimSpace(ss[1])
		if key == "" {
			return attributes, fmt.Errorf("attribute has empty value at %s", line)
		}
		attributes[key] = value
```
value should be checked instead of key.

### PR DESCRIPTION
**Pull request by chengwenxi**
Closes #739

### CODE REVIEW

File: client/distribution/lcd/query.go [hunk 1]
```diff
@@ -58,6 +58,10 @@ func QueryDelegatorDistInfoHandlerFn(storeName string, cliCtx context.CLIContext
 			utils.WriteErrorResponse(w, http.StatusBadRequest, err.Error())
 			return
 		}
+		if len(resKVs) == 0 {
+			utils.WriteErrorResponse(w, http.StatusNoContent, "")
+			return
+		}
```
Comment (HaoyangLiu) [inline client/distribution/lcd/query.go]: Just return an empty array.
